parameters:
    env(DATABASE_URL): ''
    database_driver: pdo_sqlsrv
    database_host: localhost
    database_port: null
    database_name: TestDB
    database_user: ''
    database_password: 'Sqlserver12&'

doctrine:
    dbal:
        # url: '%env(resolve:DATABASE_URL)%'
        driver: '%database_driver%'
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
